title: Collaborative IT
email: contact@joshkeisler.com
description: >- 
  Collaborative IT is an IT service provider that helps Allied Health businesses improve their service delivery,
  reduce their admin burden, and advance their clinical practice.
baseurl: "" 
url: "https://collaborative-it.joshkeisler.com" 

author:
  name: Josh Keisler
  email: contact@joshkeisler.com

social:
  name: Collaborative IT
  links:
    - https://www.linkedin.com/in/josh-keisler/

# twitter:
#   username: YOUR_TWITTER_HANDLE

# SEO & Analytics
google_analytics: G-DT1W3LWKNP 
logo: /assets/images/logo.png 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
